spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml
  jpa:
    properties:
      hibernate:
        default_schema: ${spring.liquibase.default-schema}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
---
spring:
  config:
    active:
      on-profile: local
  liquibase:
    contexts: local
    user: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/pnu_system
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  elasticsearch:
    uris: http://localhost:9200

  rabbitmq:
    username: rabbit
    password: password

internal:
  user:
    login: internal.user@timetable.com
    password: 1234

baseUrl:
  identity_access: http://localhost:7000
  lesson_location: http://localhost:7001
  academic_catalog: http://localhost:7002
  group: http://localhost:7003
  timetable: http://localhost:7004

messaging:
  rabbit:
    topic: timetable.topic

---
spring:
  config:
    active:
      on-profile: production

