spring:
  datasource:
    username: timetable_user
    password: 12345
  liquibase:
    database-change-log-table: dbchangelog_timetable_ms
    database-change-log-lock-table: dbchangeloglock_timetable_ms
    liquibase-schema: liquibase
    default-schema: timetable_microservice

---
spring:
  config:
    active:
      on-profile: local

---
spring:
  config:
    active:
      on-profile: production

