spring:
  datasource:
    username: academic_catalog_user
    password: 12345
  liquibase:
    database-change-log-table: dbchangelog_academic_catalog_ms
    database-change-log-lock-table: dbchangeloglock_academic_catalog_ms
    liquibase-schema: liquibase
    default-schema: academic_catalog_microservice

---
spring:
  config:
    active:
      on-profile: local

---
spring:
  config:
    active:
      on-profile: production

