spring:
  datasource:
    username: timetable_user
    password: 12345
  liquibase:
    database-change-log-table: dbchangelog_timetable_ms
    database-change-log-lock-table: dbchangeloglock_timetable_ms
    liquibase-schema: liquibase
    default-schema: timetable_microservice

---
spring:
  config:
    active:
      on-profile: local

messaging:
  rabbit:
    queue:
      user:
        update: timetable-user-update-queue
        delete: timetable-user-delete-queue
      subject:
        update: timetable-subject-update-queue
        delete: timetable-subject-delete-queue
      location:
        update: timetable-location-update-queue
        delete: timetable-location-delete-queue
      group:
        update: timetable-group-update-queue
        delete: timetable-group-delete-queue

---
spring:
  config:
    active:
      on-profile: production

